### ISSUE TITLE
Use dedicated type for StateHandle instead of Rc<dyn Fn>

### ISSUE THREAD

**Issue by Kestrer** [lukechu10/maple#14]
Changing `StateHandle` and `SetStateHandle` to be a dedicated type instead of just a function would increase type safety, as users won't  be able to accidentially mix up state handles and functions that are used for other things. Additionally it may improve performance since dynamic dispatch is not used. It does slightly reduce ergonomics - `.get()` would probably have to be used instead of just calling the function - but at least to me that feels more natural anyway. What do you think?

**Comment by lukechu10** [comment]
Sounds like a valid reason, though I would prefer not to have a `.get()` method. Personally, I find it a bit weird to return something just to call `.get()` on, unless of course we combine the getter and setter into a single struct (which introduces other problems). I'll do some playing around to see how this would work. Since `fn_traits` is feature gated, I might workaround this by implementing `Deref<Fn>`...

**Comment by lukechu10** [comment]
BTW @Kestrer if you want to implement this, feel free to open a PR. If not, I'll do it :)

**Comment by Kestrer** [comment]
I would like to try and implement this, hopefully I can send a PR soon.
